/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#ffffff",
        "secondary": "#4F46E5",
        "primary-fixed": "#6366f1",
        "on-background": "#dee5ff",
        "on-tertiary-fixed-variant": "#1e1b4b",
        "surface-tint": "#4F46E5",
        "surface-container": "#0f1930",
        "on-primary-container": "#e0e7ff",
        "secondary-container": "#4F46E5",
        "primary": "#4F46E5",
        "surface-dim": "#060e20",
        "surface-container-lowest": "#000000",
        "primary-fixed-dim": "#4F46E5",
        "on-surface": "#dee5ff",
        "primary-dim": "#4338ca",
        "tertiary-fixed": "#818cf8",
        "on-primary": "#ffffff",
        "error-dim": "#d73357",
        "surface-container-highest": "#192540",
        "on-secondary-fixed-variant": "#3730a3",
        "inverse-on-surface": "#4d556b",
        "on-tertiary-fixed": "#e0e7ff",
        "on-error": "#490013",
        "on-secondary": "#ffffff",
        "primary-container": "#4F46E5",
        "outline": "#6d758c",
        "tertiary-dim": "#4F46E5",
        "on-surface-variant": "#a3aac4",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#ffffff",
        "tertiary": "#818cf8",
        "surface-variant": "#192540",
        "on-tertiary-container": "#e0e7ff",
        "error-container": "#a70138",
        "secondary-fixed-dim": "#818cf8",
        "inverse-surface": "#faf8ff",
        "tertiary-fixed-dim": "#818cf8",
        "surface-container-low": "#091328",
        "surface": "#060e20",
        "secondary-dim": "#4F46E5",
        "background": "#060e20",
        "surface-container-high": "#141f38",
        "on-error-container": "#ffb2b9",
        "on-primary-fixed-variant": "#3730a3",
        "inverse-primary": "#4F46E5",
        "outline-variant": "#40485d",
        "secondary-fixed": "#c7d2fe",
        "on-secondary-fixed": "#1e1b4b",
        "tertiary-container": "#4F46E5",
        "surface-bright": "#1f2b49",
        "error": "#ff6e84"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
